### ISSUE TITLE
Can't open Jerry

### ISSUE THREAD

**Issue by partik1** [asdfjkl/jerry#10]
I've been using Jerry for a few days now and yesterday it stopped working, for some reason. Whenever I try to open Jerry, a window flashes and Jerry crashes. This is the message I get:

```
jerry
'NoneType' object has no attribute 'root'
Traceback (most recent call last):
  File "./jerry.py", line 61, in <module>
    main = MainWindow()
  File "/usr/share/jerry/main_window.py", line 54, in __init__
    self.moves_edit_view.on_statechanged()
  File "/usr/share/jerry/views/moves_edit_view.py", line 264, in on_statechanged
    self.update_san()
  File "/usr/share/jerry/views/moves_edit_view.py", line 268, in update_san
    txt = self.gs.printer.to_san_html(self.gs.current)
  File "/usr/share/jerry/views/game_gui_printer.py", line 57, in to_san_html
    current.root().export_html(exporter,current,self.offset_table)
AttributeError: 'NoneType' object has no attribute 'root'
QThread: Destroyed while thread is still running
```

I'm using Ubuntu 14.04.

**Comment by asdfjkl** [comment]
try deleting ~/.local/share/jerry200

**Comment by partik1** [comment]
Hey @asdfjkl, that solves the problem. Though it keeps happening when I'm analyzing a position and I click on the moves list. Figured you'd want to know.

**Comment by asdfjkl** [comment]
noted, thx.
I'll close this, as there will be no bugfixes for version 2. Stay posted for version 3.
