### ISSUE TITLE
UnboundLocalError

### ISSUE THREAD

**Issue by rain0r** [asdfjkl/jerry#4]
Got this message on starting jerry with python 3.4.3 on linux:

commit 496c069214546049c93f0385190e829dba049a12

```
[Errno 2] file or directory not found: '/home/foobar/.local/share/jerry200/current.raw'
[Errno 2] file or directory not found: '/home/foobar/.local/share/jerry200/settings.raw'
[Errno 2] file or directory not found: '/home/foobar/.local/share/jerry200/db_idx.raw'
Traceback (most recent call last):
  File "jerry.py", line 62, in <module>
    main = MainWindow()
  File "/home/foobar/git/jerry/main_window.py", line 46, in __init__
    self.model = Model.create_on_startup(self)
  File "/home/foobar/git/jerry/model/model.py", line 76, in create_on_startup
    database = db.Database(default_db_path)
UnboundLocalError: local variable 'db' referenced before assignment
QThread: Destroyed while thread is still running

```

**Comment by asdfjkl** [comment]
I am in the middle of refactoring the whole code into a more MVC like structure. Hence current commits won't start or are full of errors. Please be patient, I'll try to put out a 2.0 alpha as soon as possible...
